import { OpenAI } from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY, // Set your API key
});

export const generateFieldsFromOpenAI = async () => {
  const prompt = `List various professional and academic fields in the world, categorized into major areas such as Technology, Health, Business, Arts, and more. Provide a concise list of fields.`;

  const response = await openai.chat.completions.create({
    model: "gpt-3.5-turbo",
    messages: [
      { role: "system", content: "You are a helpful assistant." },
      { role: "user", content: prompt },
    ],
    max_tokens: 200,
  });

  const fieldsText = response.choices[0]?.message?.content.trim();

  if (!fieldsText) {
    throw new Error("No fields were generated by OpenAI.");
  }

  // Split the text into an array of fields
  return fieldsText
    .split("\n")
    .map((field) => field.trim())
    .filter(Boolean);
};
